name: Add Tool
run-name: Add ${{ inputs.toolName }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      toolName:
        description: 'Tool Name'
        type: string
        required: true

jobs:
  add-space:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run node script to create a gitbook space and team
        id: node
        env:
          TOOL_NAME: ${{ inputs.toolName }}
          GITBOOK_API_TOKEN: ${{ secrets.GITBOOK_API_TOKEN }}
        run: node add-space.mjs $TOOL_NAME

  add-tool:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run node script to generate new tool
        id: node
        env:
          TOOL_NAME: ${{ inputs.toolName }}
        run: |
          node add-tool.mjs $TOOL_NAME

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add $TOOL_NAME"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: add-tool-${{ inputs.toolName }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: add-tool-${{ inputs.toolName }}
          commit-message: "Add Tool: ${{ inputs.toolName }}"
          title: "Add Tool: ${{ inputs.toolName }}"
          body: "This pull request adds a new tool."
