name: Add Tool
run-name: Add ${{ inputs.toolName }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      toolName:
        description: 'Tool Name'
        type: string
        required: true

jobs:
  add-space:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Create Gitbook Space and Team (click here!)
        id: node
        env:
          TOOL_NAME: ${{ inputs.toolName }}
          GITBOOK_API_TOKEN: ${{ secrets.GITBOOK_API_TOKEN }}
        run: node add-space.mjs $TOOL_NAME

  add-tool:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Create new tool folder
        id: node
        env:
          TOOL_NAME: ${{ inputs.toolName }}
        run: |
          node add-tool.mjs $TOOL_NAME

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          base: HEAD
          filters: |
            tools:
              - 'gitbook/tools/**'

      - name: Commit changes
        if: steps.changes.outputs.tools == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add $TOOL_NAME"

      - name: Push changes
        if: steps.changes.outputs.tools == 'true'
        uses: ad-m/github-push-action@master
        with:
          branch: main

