name: Tools Updated
run-name: Check for tool updates - Run ${{ github.run_number }}

on:
  schedule:
    - cron: '0 12 1 * *'
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: All tools up to date?
        run: |
          git log --since="1 month ago" --format=oneline
          node src/last-updated.mjs

