name: Tools Updated

on:
  schedule:
    - cron: '0 12 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run node script to update categories
        run: |
          node last-updated.mjs

