name: CSV Nightly

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run node script to update csv
        run: |
          node src/csv.mjs

      - name: Create a release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: csv
          name: "Bellingcat's Online Investigation Toolkit CSV Export"
          body: "See Assets below for CSV downloads by category. Updated nightly."
          files: csv/*.csv
