name: CSV release

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Create a release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: "Bellingcat's Online Investigation Toolkit"
          body: "See Assets below for CSV downloads by category."
          prerelease: true
          files: csv/*.csv
